### PR TITLE
fix(optimism): Node Tests

### LINKED ISSUE #45: Fix Optimism Transaction Pool Tests
### Describe the feature

PR #35 introduces an executor into the transaction pool that requires the validation transaction type to be `OpTransactionSigned`.

This breaks testing in the txpool, specifically [here](https://github.com/ethereum-optimism/op-reth/blob/optimism/crates/optimism/node/src/txpool.rs#L448-L496) because the `MockEthProvider` only implements traits over the generic `Tx`, but the Optimism transaction pool requires the concrete `OpTransactionSigned` tx type now.

**Solution**

This ticket is to implement a wrapper type around `MockEthProvider` in the `reth-optimism-node` test utils [here](https://github.com/ethereum-optimism/op-reth/blob/optimism/crates/optimism/node/src/utils.rs) with the transaction set to `OpTransactionSigned` and all required traits implemented.

e.g.
```rust
#[derive(Debug, Clone)]
pub struct OpEthProvider {
    /// The inner provider.
    inner: MockEthProvider<OpTransactionSigned>,
}
```

### Additional context

Ref: https://github.com/ethereum-optimism/op-reth/pull/35#discussion_r1931274232

### PR DESCRIPTION
**Pull request by refcell**
### Description

Fixes node tests in the transaction pool using the updated `OpTransactionSigned`. This requires implementing traits on the `MockEthProvider` with the concrete generic instead of the default `T = TransactionSigned` generic.

Closes #45

### CODE REVIEW

File: crates/net/network/benches/broadcast.rs [hunk 1]
```diff
@@ -31,7 +31,8 @@ pub fn broadcast_ingress_bench(c: &mut Criterion) {
                 // runtime context and simply calling `block_on` here will cause the code to panic.
                 tokio::task::block_in_place(|| {
                     tokio::runtime::Handle::current().block_on(async {
-                        let provider = MockEthProvider::default();
+                        use reth_primitives::TransactionSigned;
+                        let provider = MockEthProvider::<TransactionSigned>::default();
```
Comment (refcell) [inline crates/net/network/benches/broadcast.rs:35]: These changes stink but i think it's unavoidable, even though i hid the op impls behind the optimism feature flag

Comment (emhane) [reply crates/net/network/benches/broadcast.rs:35]: eventually we want to remove those op feature flags anyway, I don't think it stinks so bad :)

**Review by emhane — APPROVED** [review]

File: crates/storage/provider/src/test_utils/mock.rs [hunk 2]
```diff
@@ -164,6 +164,26 @@ impl StateCommitmentProvider for MockEthProvider {
     type StateCommitment = <MockNode as NodeTypes>::StateCommitment;
```
Comment (emhane) [inline crates/storage/provider/src/test_utils/mock.rs:164]:
```suggestion
impl<T> StateCommitmentProvider for MockEthProvider<T> {
    type StateCommitment = <MockNode as NodeTypes>::StateCommitment;
```
this is instead fixed by generalising the impls. in some cases you may need trait bound `T: reth_primitive_traits::SignedTransaction`

Comment (emhane) [reply crates/storage/provider/src/test_utils/mock.rs:164]: this change is what we want to upstream, but I'm merging this pr into the base branch anyway to unblock

Comment (emhane) [reply crates/storage/provider/src/test_utils/mock.rs:164]: opened an issue https://github.com/paradigmxyz/reth/issues/14038
